language: python
python:
    - "2.7"
install:
    - python setup.py install
    - pip install pymongo redis pika MySQL-python
script:
    - py.test -v -s tests
after_script: cat erl_crash.dump
after_failure: cat erl_crash.dump
