language: python
python:
    - "2.7"
install:
    - python setup.py install
    - pip install pika
script:
    - py.test -s -vvv -k rabbit tests
env:
  global:
    - TIMEOUT=100
notifications:
    email: false